### ISSUE TITLE
Ambiguous call to function repo/0 on `mix ecto.migrate` - Phoenix 1.4

### ISSUE THREAD

**Issue by wolves** [infinitered/thesis-phoenix#155]
First, thank you for dedicating time to such a cool package for the community.

I recently did a fresh phoenix app to check it out and ran into the provided error during the migration step. To clarify, the project itself has absolutely no changes to it from a fresh Phoenix app other than adding thesis to the `mix.exs` file as instructed and following the directions provided in the Readme

```
Generated phoenix_ecto app
*   creating lib/ies/thesis_auth.ex
*   creating priv/repo/migrations/20181208145113_create_thesis_tables.exs
*   creating priv/repo/migrations/20181208145114_add_meta_to_thesis_page_contents.exs
*   creating priv/repo/migrations/20181208145115_add_indexes_to_tables.exs
*   creating priv/repo/migrations/20181208145116_add_template_and_redirect_url_to_thesis_pages.exs
*   creating priv/repo/migrations/20181208145117_change_content_default_for_page_content.exs
*   creating priv/repo/migrations/20181208145118_create_thesis_files_table.exs
*   creating priv/repo/migrations/20181208145119_create_thesis_backups_table.exs
*   creating priv/repo/migrations/20181208145120_change_and_convert_page_data_type_in_backups_table.exs
*   updating config/config.exs
*   updating web.ex
*       done Now run mix ecto.migrate to ensure your database is up to date.
Compiling 14 files (.ex)
Generated ies app
[debug] QUERY OK source="schema_migrations" db=0.8ms
SELECT s0."version"::bigint FROM "schema_migrations" AS s0 FOR UPDATE []
warning: variable "timestamps" does not exist and is being expanded to "timestamps()", please use parentheses to remove the ambiguity or change the variable name
  priv/repo/migrations/20181208145113_create_thesis_tables.exs:20

[info] == Running 20181208145113 Ies.Repo.Migrations.CreateThesisTables.change/0 forward
[info] create table thesis_pages
[info] create table thesis_page_contents
[info] == Migrated 20181208145113 in 0.0s
[info] == Running 20181208145114 Ies.Repo.Migrations.AddMetaToThesisPageContents.change/0 forward
[info] alter table thesis_page_contents
[info] == Migrated 20181208145114 in 0.0s
[info] == Running 20181208145115 Ies.Repo.Migrations.AddIndexToTables.up/0 forward
[info] alter table thesis_pages
[info] create index thesis_pages_slug_index
[info] alter table thesis_page_contents
[info] == Migrated 20181208145115 in 0.0s
[info] == Running 20181208145116 Ies.Repo.Migrations.AddTemplateAndRedirectUrlToThesisPages.change/0 forward
[info] alter table thesis_pages
[info] == Migrated 20181208145116 in 0.0s
[info] == Running 20181208145117 Ies.Repo.Migrations.ChangeContentDefaultForPageContent.up/0 forward
[info] alter table thesis_page_contents
[info] == Migrated 20181208145117 in 0.0s
[info] == Running 20181208145118 Ies.Repo.Migrations.CreateThesisFilesTable.change/0 forward
[info] create table thesis_files
[info] create index thesis_files_slug_index
[info] == Migrated 20181208145118 in 0.0s
[info] == Running 20181208145119 Ies.Repo.Migrations.CreateThesisBackupsTable.change/0 forward
[info] create table thesis_backups
[info] == Migrated 20181208145119 in 0.0s
** (CompileError) priv/repo/migrations/20181208145120_change_and_convert_page_data_type_in_backups_table.exs:35: function repo/0 imported from both Thesis.Config and Ecto.Migration, call is ambiguous
    (elixir) src/elixir_dispatch.erl:111: :elixir_dispatch.expand_import/6
    (elixir) src/elixir_dispatch.erl:81: :elixir_dispatch.dispatch_import/5
    priv/repo/migrations/20181208145120_change_and_convert_page_data_type_in_backups_table.exs:34: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:715: Code.load_file/2
    (ecto_sql) lib/ecto/migrator.ex:475: Ecto.Migrator.extract_module/2
    (ecto_sql) lib/ecto/migrator.ex:432: anonymous fn/5 in Ecto.Migrator.do_migrate/4
```

**Comment by jamonholmgren** [comment]
Thanks for the kind words, @wolves ! Would you want to take a stab at fixing this bug?

**Comment by wolves** [comment]
I am willing to take a look into it absolutely but in the spirit of full disclosure, I feel I am still relatively new to elixir. I will give it a shot as it's a great opportunity to learn but may need to reach out for assistance if I get stuck.

**Comment by wolves** [comment]
That was much more basic than expected, ha! Assuming my solution is acceptable of course.

**Comment by jamonholmgren** [comment]
@wolves Thank you! I'll take a look.
