### ISSUE TITLE
Migration 'ChangeAndConvertPageDataTypeInBackupsTable' raises an error when in prod as an Elixir release

### ISSUE THREAD

**Issue by sfusato** [infinitered/thesis-phoenix#169]
This is the error I receive:
```
18:56:55.804 [info] == Running 20191109113807 PhoenixApp.Repo.Migrations.ChangeAndConvertPageDataTypeInBackupsTable.change/0 forward
** (UndefinedFunctionError) function nil.all/1 is undefined
    nil.all(Thesis.Backup)
    _build/prod/rel/phoenixapp/lib/phoenixapp-0.3.0-beta/priv/phoenixapp/migrations/20191109113807_change_and_convert_page_data_type_in_backups_table.exs:17: PhoenixApp.Repo.Migrations.ChangeAndConvertPageDataTypeInBackupsTable.convert_and_map_page_data/0
    _build/prod/rel/phoenixapp/lib/phoenixapp-0.3.0-beta/priv/repo/migrations/20191109113807_change_and_convert_page_data_type_in_backups_table.exs:9: PhoenixApp.Repo.Migrations.ChangeAndConvertPageDataTypeInBackupsTable.change/0
    (ecto_sql) lib/ecto/migration/runner.ex:278: Ecto.Migration.Runner.perform_operation/3
    (stdlib) timer.erl:166: :timer.tc/1
    (ecto_sql) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/7
    (ecto_sql) lib/ecto/migrator.ex:342: Ecto.Migrator.attempt/7
    (ecto_sql) lib/ecto/migrator.ex:243: anonymous fn/4 in Ecto.Migrator.do_up/4
```
No issues whatsoever in dev on localhost.

**Comment by sfusato** [comment]
The error has to do with how the config is loaded in production (differently than in dev obviously).
I had to make sure `:thesis` app is loaded in prod before attempting the migrations: `Application.load(:thesis)`
